# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='overlay_banner_description_1',
            field=wagtail.core.fields.RichTextField(default='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_banner_description_2',
            field=wagtail.core.fields.RichTextField(default='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_banner_description_3',
            field=wagtail.core.fields.RichTextField(default='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_banner_description_4',
            field=wagtail.core.fields.RichTextField(default='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_banner_thumb_image_1',
            field=models.ForeignKey(help_text='150x150 pixel image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_banner_thumb_image_2',
            field=models.ForeignKey(help_text='150x150 pixel image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_banner_thumb_image_3',
            field=models.ForeignKey(help_text='150x150 pixel image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_banner_thumb_image_4',
            field=models.ForeignKey(help_text='150x150 pixel image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_banner_title_1',
            field=models.TextField(default='Your Career starts here'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_banner_title_2',
            field=models.TextField(default='Your Career starts here'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_banner_title_3',
            field=models.TextField(default='Your Career starts here'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_banner_title_4',
            field=models.TextField(default='Your Career starts here'),
        ),
    ]
