# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0002_auto_20170426_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_tiu_description',
            field=wagtail.core.fields.RichTextField(default='Description of TIU'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_tiu_title',
            field=models.TextField(default='About TIU'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_banner_description_1',
            field=wagtail.core.fields.RichTextField(default='description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_banner_description_2',
            field=wagtail.core.fields.RichTextField(default='description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_banner_title_1',
            field=models.TextField(default='For a better education'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_banner_title_2',
            field=models.TextField(default='For a better education'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_image_1',
            field=models.ForeignKey(help_text='1920x1280 pixel image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_image_2',
            field=models.ForeignKey(help_text='1920x1280 pixel image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='state_faith_description',
            field=wagtail.core.fields.RichTextField(default='Description of Faith'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='state_faith_title',
            field=models.TextField(default='Statement of Faith'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='state_mission_description',
            field=wagtail.core.fields.RichTextField(default='Description of mission'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='state_mission_title',
            field=models.TextField(default='Statement of Mission'),
        ),
    ]
