# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0004_homepage_our_mission_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='chairman_image',
            field=models.ForeignKey(help_text='342 x 478 pixels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='chairman_message',
            field=wagtail.core.fields.RichTextField(default='Message'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='chairman_title',
            field=models.TextField(default="Chairman's Welcome"),
        ),
        migrations.AddField(
            model_name='homepage',
            name='president_image',
            field=models.ForeignKey(help_text='342 x 478 pixels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='president_message',
            field=wagtail.core.fields.RichTextField(default='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='president_title',
            field=models.TextField(default="President's Welcome"),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tyndale_image',
            field=models.ForeignKey(help_text='342 x 478 pixels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tyndale_message',
            field=wagtail.core.fields.RichTextField(default='Message'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tyndale_title',
            field=models.TextField(default='Learn about Tyndale'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='yala_image',
            field=models.ForeignKey(help_text='342 x 478 pixels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='yala_message',
            field=wagtail.core.fields.RichTextField(default='message'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='yala_title',
            field=models.TextField(default='Learn about Yala'),
        ),
    ]
