# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0012_auto_20170428_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairmanwelcomepage',
            name='message',
            field=wagtail.wagtailcore.fields.RichTextField(default='Message'),
        ),
        migrations.AddField(
            model_name='chairmanwelcomepage',
            name='name',
            field=models.CharField(default='Joen Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='chairmanwelcomepage',
            name='position',
            field=models.CharField(default='President', help_text='President', max_length=100),
        ),
        migrations.AddField(
            model_name='chairmanwelcomepage',
            name='profile_image',
            field=models.ForeignKey(help_text='263x263 pixels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='chairmanwelcomepage',
            name='spec',
            field=models.CharField(default='Ph.D', help_text='Ph.D, D.D', max_length=100),
        ),
    ]
