# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='order_number',
            field=models.IntegerField(default=10),
        ),
    ]
