# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20170428_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprogramdetailpage',
            name='order_number',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='academicprogramdetailpage',
            name='academic_image',
            field=models.ForeignKey(help_text='265x265 pixels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
