# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20170429_0101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseListPage',
            new_name='CourseDescriptionPage',
        ),
    ]
