# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0023_auto_20170502_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(default='Mar 2017', help_text='Start Date of course', max_length=100)),
                ('semester_name', models.CharField(default='Spring of 2017', help_text='Name of semester', max_length=100)),
                ('semester_duration', models.CharField(default='Mar 24 - June 25', help_text='Duration of semester', max_length=100)),
                ('semester_thumb_image', models.ForeignKey(help_text='554x674 pixel image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
