# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_courseindexpage_semester_semesterpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterpage',
            name='semester_subtitle',
            field=models.TextField(default='Here is our all course'),
        ),
        migrations.AddField(
            model_name='semesterpage',
            name='semester_title',
            field=models.CharField(default='Choose Semester', max_length=100),
        ),
    ]
