# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('home', '0027_auto_20170502_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselistpage',
            name='course_intro',
            field=wagtail.core.fields.RichTextField(default='Brief introduction of course'),
        ),
        migrations.AddField(
            model_name='courselistpage',
            name='course_name',
            field=models.TextField(default='Course Name'),
        ),
        migrations.AddField(
            model_name='courselistpage',
            name='thumb_image',
            field=models.ForeignKey(help_text='500 x 500 image for course intro page ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
