# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20170505_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='grid_url',
            field=models.CharField(default='/academic-program', max_length=100),
        ),
    ]
