# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_homepage_grid_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='grid_url',
            field=models.CharField(default='/academics/academic-program', max_length=100),
        ),
    ]
