# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('home', '0032_auto_20170505_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='grid_url',
        ),
        migrations.AddField(
            model_name='homepage',
            name='grid_link_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
