# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0033_auto_20170505_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='quote_message',
            field=wagtail.wagtailcore.fields.RichTextField(default='quote_message'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_profile_image',
            field=models.ForeignKey(help_text='50x50 pixels image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_speaker',
            field=models.CharField(default='Taehwan Kim', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_speaker_title',
            field=models.CharField(default='Senior Pastor', max_length=100),
        ),
    ]
