# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [

        ('home', '0034_auto_20170505_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_message', wagtail.wagtailcore.fields.RichTextField(default='quote_message')),
                ('quote_speaker', models.CharField(default='Taehwan Kim', max_length=50)),
                ('quote_speaker_title', models.CharField(default='Senior Pastor', max_length=100)),
                ('quote_profile_image', models.ForeignKey(help_text='50x50 pixels image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_message',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_profile_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_speaker',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quote_speaker_title',
        ),
    ]
