# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20170505_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='quotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.Quote'),
        ),
    ]
