# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_homepage_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageQuotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Quote for Homepage',
                'verbose_name_plural': 'Quotes for Homepage',
            },
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='quotes',
        ),
        migrations.AddField(
            model_name='homepagequotes',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_quote', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='homepagequotes',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.Quote'),
        ),
    ]
