# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0037_auto_20170505_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSliderMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Message for slider',
                'verbose_name_plural': 'Messages for slider',
            },
        ),
        migrations.CreateModel(
            name='SliderMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Good is good', max_length=100)),
                ('message', wagtail.core.fields.RichTextField(default='Message')),
                ('image', models.ForeignKey(help_text='150x150 pixel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.AddField(
            model_name='homepageslidermessages',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.SliderMessage'),
        ),
        migrations.AddField(
            model_name='homepageslidermessages',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_message', to='home.HomePage'),
        ),
    ]
