# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20170505_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='overlay_banner_description_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='overlay_banner_description_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='overlay_banner_description_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='overlay_banner_description_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='overlay_banner_thumb_image_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='overlay_banner_thumb_image_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='overlay_banner_thumb_image_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='overlay_banner_thumb_image_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='overlay_banner_title_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='overlay_banner_title_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='overlay_banner_title_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='overlay_banner_title_4',
        ),
    ]
