# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20170505_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='slider_banner_description_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_banner_description_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_banner_title_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_banner_title_2',
        ),
    ]
