# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20170505_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', wagtail.core.fields.RichTextField(default='Some News')),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='popup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.Popup'),
        ),
    ]
