# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0042_newsdetailpage_newspage_tyndalenews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TyndaleNews',
        ),
        migrations.AddField(
            model_name='newsdetailpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsdetailpage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsdetailpage',
            name='news_content',
            field=wagtail.wagtailcore.fields.RichTextField(default='News Content'),
        ),
        migrations.AddField(
            model_name='newsdetailpage',
            name='news_title',
            field=models.CharField(default='News Title', max_length=255),
        ),
        migrations.AddField(
            model_name='newspage',
            name='banner_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
